# Generated by Django 2.2.12 on 2020-05-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(editable=False, upload_to='certificates/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('latex_document', models.CharField(editable=False, max_length=100)),
            ],
        ),
    ]
