# Generated by Django 2.2.12 on 2020-05-20 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preprintrecorder', '0003_preprintrecord_process'),
        ('certificatestore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='parent_record_in_priprint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='preprintrecorder.PrePrintRecord'),
            preserve_default=False,
        ),
    ]
