# Generated by Django 2.2.12 on 2020-05-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificatestore', '0002_certificate_parent_record_in_priprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='test',
            field=models.CharField(default=2323, max_length=100),
            preserve_default=False,
        ),
    ]
