# Generated by Django 2.2.12 on 2020-05-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificatestore', '0003_certificate_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='latex_document',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='upload',
            field=models.FileField(upload_to='certificates/'),
        ),
    ]
