# Generated by Django 2.2.12 on 2020-05-20 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificatestore', '0004_auto_20200520_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='parent_record_in_priprint',
            new_name='parent_record',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='test',
        ),
    ]
