# Generated by Django 2.2.12 on 2020-05-20 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificatestore', '0005_auto_20200520_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='latex_document',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='parent_record',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='preprintrecorder.PrePrintRecord'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='upload',
            field=models.FileField(editable=False, upload_to='certificates/'),
        ),
    ]
