# Generated by Django 2.2.12 on 2020-05-20 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('latexprocessor', '0001_initial'),
        ('certificatestore', '0006_auto_20200520_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='latex_process',
            field=models.ForeignKey(default=2, editable=False, on_delete=django.db.models.deletion.PROTECT, to='latexprocessor.LatexProcess'),
            preserve_default=False,
        ),
    ]
