# Generated by Django 2.2.12 on 2020-05-22 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificatestore', '0007_certificate_latex_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='latex_process',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='latexprocessor.LatexProcess'),
        ),
    ]
