# Generated by Django 2.2.12 on 2020-05-22 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificatestore', '0008_auto_20200522_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='latex_process',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='latexprocessor.LatexProcess'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='parent_record',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='preprintrecorder.PrePrintRecord'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='upload',
            field=models.FilePathField(editable=False),
        ),
    ]
