# Generated by Django 2.2.12 on 2020-05-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificatestore', '0009_auto_20200522_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(editable=False, upload_to='%Y/%m/%d/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='upload',
        ),
    ]
