# Generated by Django 2.2.12 on 2020-05-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificatestore', '0010_auto_20200525_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='upload',
            field=models.FileField(default=1, upload_to='certificates'),
            preserve_default=False,
        ),
    ]
