# Generated by Django 2.2.12 on 2020-05-27 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificatestore', '0011_certificate_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateOrgy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CheckCertificate',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='latex_process',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='latexprocessor.LatexProcess'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='parent_record',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preprintrecorder.PrePrintRecord'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='orgy',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificatestore.CertificateOrgy'),
        ),
    ]
