# Generated by Django 2.2.12 on 2020-05-27 15:25

import certificatestore.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificatestore', '0012_auto_20200527_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='filename',
            field=models.CharField(default=2243, editable=False, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='orgy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificatestore.CertificateOrgy'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='upload',
            field=models.FileField(upload_to=certificatestore.models.set_path_and_filename),
        ),
    ]
