# Generated by Django 2.2.12 on 2020-05-27 15:32

import certificatestore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificatestore', '0013_auto_20200527_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=certificatestore.models.set_path_and_filename),
        ),
    ]
