# Generated by Django 2.2.12 on 2020-05-27 15:41

import certificatestore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificatestore', '0014_auto_20200527_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(blank=True, null=True, upload_to=certificatestore.models.set_path_and_filename)),
                ('filename', models.CharField(editable=False, max_length=200)),
            ],
        ),
    ]
