# Generated by Django 2.2.12 on 2020-05-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificatestore', '0015_testcertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcertificate',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='certificates'),
        ),
    ]
