# Generated by Django 2.2.12 on 2020-05-29 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificatestore', '0016_auto_20200527_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='upload',
        ),
    ]
