# Generated by Django 2.2.12 on 2020-05-29 07:23

import certificatestore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificatestore', '0017_remove_certificate_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='upload',
            field=models.FilePathField(default=1, editable=False, path=certificatestore.models.set_path_and_filename),
            preserve_default=False,
        ),
    ]
