# Generated by Django 2.2.12 on 2020-05-29 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificatestore', '0018_certificate_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestCertificate',
        ),
    ]
