# Generated by Django 2.2.12 on 2020-05-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificatestore', '0019_delete_testcertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='upload',
            field=models.FilePathField(editable=False),
        ),
    ]
