# Generated by Django 2.2.12 on 2020-05-29 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificatestore', '0020_auto_20200529_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='orgy',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificatestore.CertificateOrgy'),
        ),
    ]
