# Generated by Django 2.2.12 on 2020-05-27 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('latexprocessor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latexprocess',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='latexprocessor.Template'),
        ),
    ]
