# Generated by Django 2.2.12 on 2020-05-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latexprocessor', '0002_auto_20200527_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='latexprocess',
            name='slug',
            field=models.SlugField(default=23),
            preserve_default=False,
        ),
    ]
