# Generated by Django 2.2.12 on 2020-05-20 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preprintrecorder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preprintrecord',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='preprintrecord',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='preprintrecord',
            old_name='surname',
            new_name='second_name',
        ),
    ]
