# Generated by Django 2.2.12 on 2020-05-20 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('latexprocessor', '0001_initial'),
        ('preprintrecorder', '0002_auto_20200520_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprintrecord',
            name='process',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='latexprocessor.LatexProcess'),
            preserve_default=False,
        ),
    ]
