# Generated by Django 2.2.12 on 2020-05-22 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preprintrecorder', '0005_auto_20200522_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprintrecord',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='latexprocessor.LatexProcess'),
        ),
    ]
