# Generated by Django 2.2.12 on 2020-05-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprintrecorder', '0006_auto_20200522_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprintrecord',
            name='gen_cert',
            field=models.BooleanField(default=False),
        ),
    ]
