# Generated by Django 2.2.12 on 2020-05-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprintrecorder', '0007_preprintrecord_gen_cert'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprintrecord',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('u', 'undefined'), ('', 'none')], max_length=1, null=True),
        ),
    ]
