# Generated by Django 2.2.12 on 2020-06-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprintrecorder', '0008_preprintrecord_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprintrecord',
            name='second_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
