# Generated by Django 2.2.12 on 2020-05-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('email_from', models.EmailField(max_length=254)),
                ('reply_to', models.EmailField(max_length=254)),
            ],
        ),
    ]
