# Generated by Django 2.2.12 on 2020-05-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='bcc_email',
            field=models.EmailField(default=344, max_length=254),
            preserve_default=False,
        ),
    ]
