# Generated by Django 2.2.12 on 2020-05-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_mailer', '0002_message_bcc_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email_from',
            field=models.CharField(max_length=254),
        ),
    ]
