# Generated by Django 2.2.12 on 2020-06-05 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificatestore', '0021_auto_20200529_1809'),
        ('custom_mailer', '0003_auto_20200531_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_to', models.EmailField(max_length=254)),
                ('result_id', models.CharField(blank=True, max_length=200)),
                ('result_status', models.CharField(blank=True, max_length=200)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificatestore.Certificate')),
            ],
        ),
    ]
