# Generated by Django 2.2.12 on 2020-06-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_mailer', '0004_messagestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='from_name',
            field=models.CharField(default=342, max_length=254),
            preserve_default=False,
        ),
    ]
