# Generated by Django 2.2.12 on 2020-06-05 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_mailer', '0005_message_from_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagestatus',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificatestore.Certificate'),
        ),
    ]
