# Generated by Django 2.2.12 on 2020-06-06 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_mailer', '0006_auto_20200606_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagestatus',
            name='certificate',
        ),
    ]
