# Generated by Django 2.2.12 on 2020-06-06 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificatestore', '0021_auto_20200529_1809'),
        ('custom_mailer', '0007_remove_messagestatus_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagestatus',
            name='certificate',
            field=models.ForeignKey(default=23134, on_delete=django.db.models.deletion.CASCADE, to='certificatestore.Certificate'),
            preserve_default=False,
        ),
    ]
