# Generated by Django 2.2.12 on 2020-06-06 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_mailer', '0008_messagestatus_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagestatus',
            name='certificate',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='certificatestore.Certificate'),
        ),
    ]
