# Generated by Django 2.2.12 on 2020-06-06 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_mailer', '0009_auto_20200606_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagestatus',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificatestore.Certificate'),
        ),
    ]
